---
title: "Sources and Descriptions"
output: html_document
---

```{r setup and load data, include=FALSE}
library(tidyverse)
load("rdas/spanish_rawdf.rda")
load("rdas/sars_us.rda")
load("rdas/sars_global.rda")
load("rdas/influenza_us_cases.rda")
load("rdas/influenza_global_cases.rda")
load("rdas/h1n1_us_cases.rda")
load("rdas/h1n1_global_cases.rda")
load("rdas/h1n1_us_deaths.rda")
load("rdas/h1n1_global_deaths.rda")
load("rdas/covid19_chicago_df.rda")
load("rdas/covid_global.rda")
load("rdas/covid_us_cases.rda")
load("rdas/covid_us_deaths.rda")
```

Data for the project was collected from the following online resources:

1. Spanish flu (Chicago):  [www.Kaggle.com](https://www.kaggle.com/thepodclub/spanish-flu-dataset)

Description: This dataset contains information on `r spanish_rawdf %>% nrow()` mortality cases, with "Unique Point Identifier (fid)", case type as pneumonia (1) or flu/unknown(0), point-location of each death(x(m) and y(m)), and week when death was recorded (as of 9/28/1918), for all the cases. Data recorded was for 7 weeks, which was during the [peak of the disease](cdc.gov/flu/pandemic-resources/1918-commemoration/three-waves.htm). 


2. SARS 2003 (Global + U.S.): [WHO.int/csr/sars/](https://www.who.int/health-topics/severe-acute-respiratory-syndrome#tab=tab_1)

Description: Data collected from March 17, 2003 to April 2, 2003 on cumulative number of cases, number of deaths, number recovered, and countries for the given date. The tidy global dataset contains `r sars_global %>% nrow()` rows of daily activity, and `r sars_global %>% ncol()`. The tidy U.S. dataset contains `r sars_us %>% nrow()` rows of daily activity, and `r sars_us %>% ncol()`.


3. H1N1 + Influenza B Cases (Global + U.S.): [apps.who.int/flumart](https://apps.who.int/flumart/Default?ReportNo=12)

Description: Flu data is available by a country or region, with range of years (starting with 1995) and range of weeks selected. It includes weekly information on the type of flu virus (A or B) detected by subtypes of five in group A and 3 in group B, total number of positive cases, total of flu-negative cases, and ILI (Influenza like Illness). ILI activity is recorded as regional, local or sporadic outbreak,  with “no report” for many countries. We normalized the datasets to contain variables of pandemic duration, number of new cases, and number of cumulative cases. The tidy dataset for global H1N1 cases contains `r h1n1_global_cases %>% nrow()` rows and `r h1n1_global_cases %>% ncol()` columns. The dataset for U.S. H1N1 cases contains `r h1n1_us_cases %>% nrow()` rows and `r h1n1_us_cases %>% ncol()` columns. The dataset for global Inlfuenza B cases contains `r influenza_global_cases %>% nrow()` rows and `r influenza_global_cases %>% ncol()` columns. The dataset for Inlfuenza B cases in the U.S. contains `r influenza_us_cases %>% nrow()` rows and `r influenza_us_cases %>% ncol()` columns.


4. H1N1 Deaths (Global + U.S.): [www.Kaggle.com](https://www.kaggle.com/imdevskp/h1n1-swine-flu-2009-pandemic-dataset)

Description: This dataset contains information about new and cumulative number of deaths resulting from the H1N1 pandemic from January 2009 to August 2010. We normalized the datasets to contain variables of pandemic duration, number of new deaths, and number of cumulative deaths. The tidy dataset for global H1N1 deaths contains `r h1n1_global_deaths %>% nrow()` rows and `r h1n1_global_deaths %>% ncol()` columns. The tidy dataset for U.S. H1N1 deaths contains `r h1n1_us_deaths %>% nrow()` rows and `r h1n1_us_deaths %>% ncol()` columns.


5. COVID-19 (Global): [covid19.who.int/table](https://covid19.who.int/table)

Description: This data by World Health Organization provides information on total cumulative cases of COVID-19, newly reported cases in last 24hrs, total deaths and deaths in last 24 hrs, and method of transmission (community, cluster, sporadic or no cases) for a country or a region. The dataset used was taken from January 3, 2020 until November 10, 2020 and was normalized for the variables of pandemic duration, number of new case, number of cumulative cases, number of new deaths, and number of cumulative deaths. The tidy dataset contains `r covid_global %>% nrow()` rows and `r covid_global %>% ncol()` columns


6. COVID-19 Cases (USA): [data.cdc.gov](https://data.cdc.gov/Case-Surveillance/COVID-19-Case-Surveillance-Public-Use-Data/vbim-akqf)

Description: The original dataset contained updated daily case counts of COVID-19 with many variables such as current status, sex, age, and ethnicity. The tidy dataset contains the variables pandemic duration, number of new cases, and number of cumulative cases and is comprised of `r covid_us_cases %>% nrow()` rows and `r covid_us_cases %>% ncol()` columns.


7. COVID-19 Deaths (USA): [data.cdc.gov](https://data.cdc.gov/NCHS/Provisional-COVID-19-Death-Counts-by-Week-Ending-D/r8kw-7aab)

Description: This dataset contains updated weekly death counts attributed to COVID-19. The tidy dataset contains the variables pandemic duration, number of new cases, and number of cumulative cases and is comprised of `r covid_us_deaths %>% nrow()` rows and `r covid_us_deaths %>% ncol()` columns.


8. COVID-19 (Chicago): [data.cityofchicago.org](https://data.cityofchicago.org/Health-Human-Services/COVID-19-Daily-Cases-Deaths-and-Hospitalizations/naz8-j4nc/data)

Description: This dataset included `r covid19_chicago_df %>% nrow()` rows of dates and `r covid19_chicago_df %>% ncol()` columns, date starting from 3/1/ 2020 to 11/22/2020. Data was collected for total cases, total deaths and total hospitalizations for each day, and stratified by age groups, sex, and ethnicity  for all the cases, deaths and hospitalizations.


9. $R_0$ and other statistical summaries: [thelancet.com](https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30484-9/fulltext)

Description: This is an article with multiple tables, with table 1 containing information on Basic Reproductive Rates of various prior pandemics and Covid-19. Data-scraping was used to extract the relevant table and information on it.

10. Country Spatial Polygon Data: [GitHub repo](https://github.com/johan/world.geo.json)

Description: This is a .JSON file containing spatial polygon data for 180 countries. Countries are identifiable by name or 3 letter country code.
