---
title: "p8105: Final project proposal"
output:
  html_document:
    toc: true
    toc_float: true
---
***
### Group members:
#### _Jared Klug (jak2312)_
#### _David Nemirovsky (dn2501)_
#### _Matthew Lawlor (ml4198)_
#### _Purnima Sharma (ps3147_)
<br><br><br><br>

### Tentative project title: 
#### ***"Future of COVID-19: Looking at past pandemics"***

### Proposal

The motivation for the project is provided by the article:
[How the pandemic might play out in 2021 and beyond](https://www.nature.com/articles/d41586-020-02278-5)

The final products of the project aim to get a view into how the current corona virus might take its course in the near future and possibly beyond, by looking into some of the past pandemics and epidemics. Comparing available data from historical infectious diseases to covid 19 in the same framework would be the aim of the project, in an effort to establish any relevant associations.
Primary data sources would be from website kaggle.com, along with cdc.gov and who.int for covid19 data.
[(Example of kaggle dataset)](https://www.kaggle.com/thepodclub/spanish-flu-dataset)

Data comparisons would be performed between past pandemics and the current pandemic using parallel datasets, by analyzing statistical parameters and their visual graphics. Challenges would be to find data on some historical pandemics from time period when data collection was not well established, along with finding current complete data on the pandemic which is still in the running. 

We anticipate to complete the project within 1 month, with setting up of basic structure of the site and importing/tidying data in week 1, numerical analysis and graphing in week 2, writing the report and webpage/screencast in weeks 3 and 4, by Dec 4 2020.     


