---
title: "Comparing Pandemics"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
runtime: shiny
---
```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(plotly)
library(flexdashboard)
library(leaflet)
library(geojsonio)
library(rsconnect)
library(shiny)
library(httr)

# deployApp('./shiny_dashboard.Rmd')
```

```{r create_df, include=FALSE}

####### Country polygons

countries <- geojson_read("./data/countries.geo.json", what = "sp")


## H1N1 data 4/24/09 to 7/6/09

h1n1_df = read_csv("./data/h1n1_data.csv") %>%
  janitor::clean_names() %>%
  group_by(country) %>%
  summarize(
    cum_cases = max(cumulative_no_of_cases),
    cum_deaths = max(cumulative_no_of_deaths)
  ) %>% 
  rename(name = country) %>% 
  mutate(
    name = str_replace(name, "Guernsey, Crown Dependency", "Guernsey"),
    name = str_replace(name, "Hong Kong Special Administrative Region", "Hong Kong"),
    name = str_replace(name, "Viet Nam", "Vietnam"),
    disease = "h1n1"
  )


# Covid Data 1/10/20 to 9/9/20
covid_df = read_csv("./data/covid19_global.csv") %>% 
  janitor::clean_names() %>% 
  group_by(country) %>% 
  summarize(
    cum_cases = max(cumulative_cases),
    cum_deaths = max(cumulative_deaths)
  ) %>% 
  mutate(
    name = country,
    name = str_replace(name, "Venezuela \\(Bolivarian Republic of\\)", "Venezuela"),
    name = str_replace(name, "Iran \\(Islamic Republic of\\)", "Iran"),
    name = str_replace(name, "Russian Federation", "Russia"),
    name = str_replace(name, "The United Kingdom", "United Kingdom"),
    name = str_replace(name, "Bolivia \\(Plurinational State of\\)", "Bolivia"),
    name = str_replace(name, "Congo", "Republic of the Congo"),
    name = str_replace(name, "Syrian Arab Republic", "Syria"),
    name = str_replace(name, "Czechia", "Czech Republic"),
    name = str_replace(name, "Serbia", "Republic of Serbia"),
    name = str_replace(name, "Republic of Moldova", "Moldova"),
    name = str_replace(name, "Guinea-Bissau", "Guinea Bissau"),
    name = str_replace(name, "Lao People's Democratic Republic", "Laos"),
    name = str_replace(name, "Viet Nam", "Vietnam"),
    name = str_replace(name, "Republic of Korea", "South Korea"),
    name = str_replace(name, "Falkland Islands (Malvinas)", "Falkland Islands"),
    name = str_replace(name, "Democratic Republic of the Republic of the Congo", "Democratic Republic of the Congo")
  ) %>% 
  select(name, cum_cases, cum_deaths) %>% 
  mutate(disease = "covid")


#SARS Data 3/17/2003 to 7/11/2003
sars_df = 
  read_csv("./data/sars_2003_complete_dataset_clean.csv") %>% 
  janitor::clean_names() %>% 
  select(-number_recovered) %>% 
  group_by(country) %>% 
  filter(date == max(date)) %>% 
  rename(
    name = country,
    cum_cases = cumulative_number_of_case_s,
    cum_deaths = number_of_deaths
  ) %>% 
  mutate(
    name = str_replace(name, "Viet Nam", "Vietnam"),
    name = str_replace(name, "Russian Federation", "Russia"),
    name = str_replace(name, "Republic of Korea", "South Korea"),
    name = str_replace(name, "United States", "United States of America")
  ) %>% 
  select(name, cum_cases, cum_deaths) %>% 
  mutate(disease = "sars")


global_pan_df = rbind(covid_df, sars_df, h1n1_df) %>%
  mutate(case_fatality_rate = cum_deaths/cum_cases * 100,
         case_fatality_rate = round(case_fatality_rate, 2)) %>% 
  relocate(disease, .after = name)
  

disease_pal = function(disease){
  if(disease == "covid") {
    pal = colorBin(palette = "YlOrRd", bins = c(1, 100, 1000, 5000, 10000, 50000, 100000, 500000, 1000000, Inf), na.color = "#808080")
  }
  
  if (disease == "sars") {
    pal = colorBin(palette = "YlOrRd", bins = c(1, 10, 100, 500, 1000, 5000, Inf), na.color = "#808080")
  }

  if(disease == "h1n1"){
    pal = colorBin(palette = "YlOrRd", bins = c(1, 10, 100, 500, 1000, 5000, 10000, 20000, Inf), na.color = "#808080")
  }
  
  pal 
}

```

Column {.sidebar}
-----------------------------------------------------------------------
```{r shiny_inputs}

# disease_choices = global_pan_df %>% pull(disease) %>% unique()
# 
# selectInput(
#   "disease_choice1",
#   h3("Map 1 Pandemic:"),
#   choices = disease_choices,
#   selected = "covid"
# )
# 
# selectInput(
#   "disease_choice2",
#   h3("Map 2 Pandemic:"),
#   choices = disease_choices,
#   selected = "h1n1"
# )
# 
# compare_choices = global_pan_df %>% select(-name, -disease) %>% names()
# 
# radioButtons(
#   "compare_choice",
#   h3("Pick Parameter to Compare"),
#   choices = compare_choices,
#   selected = "cum_cases"
# )


```

Row {data-height=650}
-------------------------------------

```{r}
# renderLeaflet({
#     sp_df = global_pan_df %>%
#     filter(disease == input[["disease_choice1"]]) %>%
#     select(name, cum_cases, cum_deaths, case_fatality_rate) %>%
#     sp::merge(x = countries, by = "name", all.x = TRUE)
# 
#     sp_df %>%
#     leaflet() %>%
#     setView(lng = -10, lat = 20, zoom = 01) %>%
#     addTiles() %>%
#     addPolygons(fillColor = ~disease_pal(input[["disease_choice1"]])(cum_cases),
#     weight = 1.5,
#     opacity = 1,
#     color = "white",
#     dashArray = "3",
#     fillOpacity = 0.7,
#     highlight = highlightOptions(
#       weight = 5,
#       color = "#666",
#       dashArray = "",
#       fillOpacity = 0.7,
#       bringToFront = TRUE),
#     popup = paste0("<strong>Country: </strong>",
#                   sp_df$name,
#                   "<br><strong># of cases: </strong>",
#                   sp_df$cum_cases,
#                   "<br><strong># of deaths: </strong>",
#                   sp_df$cum_deaths,
#                   "<br><strong>Case-fatality rate: </strong>",
#                   sp_df$case_fatality_rate, "%")) %>%
#     addLegend(
#       "bottomright",
#       pal = disease_pal(input[["disease_choice1"]]),
#       values = ~cum_cases,
#       title = "# Cases",
#       opacity = 1
#     )
# })
```

```{r}
# renderLeaflet({
#     sp_df = global_pan_df %>%
#     filter(disease == input[["disease_choice2"]]) %>%
#     select(name, cum_cases, cum_deaths, case_fatality_rate) %>%
#     sp::merge(x = countries, by = "name", all.x = TRUE)
# 
#     sp_df %>%
#     leaflet() %>%
#     setView(lng = -10, lat = 20, zoom = 01) %>%
#     addTiles() %>%
#     addPolygons(fillColor = ~disease_pal(input[["disease_choice2"]])(cum_cases),
#     weight = 1.5,
#     opacity = 1,
#     color = "white",
#     dashArray = "3",
#     fillOpacity = 0.7,
#     highlight = highlightOptions(
#       weight = 5,
#       color = "#666",
#       dashArray = "",
#       fillOpacity = 0.7,
#       bringToFront = TRUE),
#     popup = paste0("<strong>Country: </strong>",
#                   sp_df$name,
#                   "<br><strong># of cases: </strong>",
#                   sp_df$cum_cases,
#                   "<br><strong># of deaths: </strong>",
#                   sp_df$cum_deaths,
#                   "<br><strong>Case-fatality rate: </strong>",
#                   sp_df$case_fatality_rate, "%")) %>%
#     addLegend(
#       "bottomright",
#       pal = disease_pal(input[["disease_choice2"]]),
#       values = ~cum_cases,
#       title = "# Cases",
#       opacity = 1
#     )
# })
```

Row {data-height=350}
-------------------------------------
```{r}
# renderPlotly({
# 
#   if(input[["disease_choice1"]] == "covid"){
#     sel_dis = "COVID-19 (1/10/20-9/9/20)"
#   }
#   if(input[["disease_choice1"]] == "sars"){
#     sel_dis = "SARS (3/17/2003-7/11/2003)"
#   }
#   if(input[["disease_choice1"]] == "h1n1"){
#     sel_dis = "H1N1 (4/24/09-7/6/09)"
#   }
# 
# 
#   if(input[["compare_choice"]] == "cum_cases"){
#     .x = ~cum_cases
#     sel_title = str_c(sel_dis, "Cumulative Cases", sep = " ")
#   }
#   if(input[["compare_choice"]] == "cum_deaths"){
#     .x = ~cum_deaths
#     sel_title = str_c(sel_dis, "Cumulative Deaths", sep = " ")
#   }
#   if(input[["compare_choice"]] == "case_fatality_rate"){
#     .x = ~case_fatality_rate
#     sel_title = str_c(sel_dis, "Case-Fatality Rate (%)", sep = " ")
#   }
# 
#   compare_df = global_pan_df %>%
#     filter(disease == input[["disease_choice1"]],
#            name %in% countries$name) %>%
#     select(name, input[["compare_choice"]])
# 
#     compare_df %>%
#     mutate(rank = rank(desc(compare_df[2])),
#            name = fct_reorder(name, desc(rank))) %>%
#     filter(rank <= 15) %>%
#     plot_ly(
#       x = .x,
#       y = ~name,
#       type = "bar") %>%
#       layout(title = sel_title,
#              xaxis = list(title = " "),
#              yaxis = list(title = "Country"))
# })
```

```{r}
# renderPlotly({
# 
#   if(input[["disease_choice2"]] == "covid"){
#     sel_dis = "COVID-19 (1/10/20-9/9/20)"
#   }
#   if(input[["disease_choice2"]] == "sars"){
#     sel_dis = "SARS (3/17/2003-7/11/2003)"
#   }
#   if(input[["disease_choice2"]] == "h1n1"){
#     sel_dis = "H1N1 (4/24/09-7/6/09)"
#   }
# 
# 
#   if(input[["compare_choice"]] == "cum_cases"){
#     .x = ~cum_cases
#     sel_title = str_c(sel_dis, "Cumulative Cases", sep = " ")
#   }
#   if(input[["compare_choice"]] == "cum_deaths"){
#     .x = ~cum_deaths
#     sel_title = str_c(sel_dis, "Cumulative Deaths", sep = " ")
#   }
#   if(input[["compare_choice"]] == "case_fatality_rate"){
#     .x = ~case_fatality_rate
#     sel_title = str_c(sel_dis, "Case-Fatality Rate (%)", sep = " ")
#   }
# 
#   compare_df = global_pan_df %>%
#     filter(disease == input[["disease_choice2"]],
#            name %in% countries$name) %>%
#     select(name, input[["compare_choice"]])
# 
#     compare_df %>%
#     mutate(rank = rank(desc(compare_df[2])),
#            name = fct_reorder(name, desc(rank))) %>%
#     filter(rank <= 15) %>%
#     plot_ly(
#       x = .x,
#       y = ~name,
#       type = "bar") %>%
#       layout(title = sel_title,
#              xaxis = list(title = " "),
#              yaxis = list(title = "Country"))
# })
```


