---
title: "Spanish flu"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(ggplot2)
library(dygraphs)
library(rvest)
library(httr)
library(janitor)
```

Spanish flu vs covid19 in Chicago (7 weeks mortality, at peak)

```{r }
spanish_rawdf = read.csv("./data/spanish_flu_chicago.csv") 

save(spanish_rawdf, file = "spanish_rawdf.rda")

spanish_df = 
  spanish_rawdf %>% 
  janitor::clean_names() %>% 
  group_by(week) %>% 
  summarize(mortality = n())

plot_1 =
spanish_df %>% 
   plot_ly(
    x = ~week, y = ~mortality, color = ~mortality, type = "bar") %>% 
  layout(title = "Spanish Flu")
```

COVID-19 Mortality (Chicago): at it's peak.
```{r}
covid19_chicago_rawdf =  read.csv("./data/covid19_chicago.csv") 

save(covid19_chicago_rawdf, file = "covid19_chicago_rawdf.rda")

covid19_chicago =
  covid19_chicago_rawdf %>% 
   janitor::clean_names() %>% 
    filter(deaths_total != 0) %>% 
   mutate(
    date = as.Date(date, "%m/%d/%y")
   ) 
  
 row1 = covid19_chicago %>%  
     filter(date >= as.Date("2020-04-07") & date <= as.Date("2020-04-13")) %>% 
     summarize(
       week = 1,
       mortality = sum(deaths_total))
 
 row2 = covid19_chicago %>%  
     filter(date >= as.Date("2020-04-14") & date <= as.Date("2020-04-20")) %>% 
     summarize(
       week = 2,
        mortality = sum(deaths_total))
 
 row3 = covid19_chicago %>%  
     filter(date >= as.Date("2020-04-21") & date <= as.Date("2020-04-27")) %>% 
     summarize(
       week = 3,
        mortality = sum(deaths_total))
 
 row4 = covid19_chicago %>%  
     filter(date >= as.Date("2020-04-28") & date <= as.Date("2020-05-04")) %>% 
     summarize(
       week = 4,
        mortality = sum(deaths_total))
 
 row5 = covid19_chicago %>%  
     filter(date >= as.Date("2020-05-05") & date <= as.Date("2020-05-11")) %>% 
     summarize(
       week = 5,
        mortality = sum(deaths_total))
 
 row6 = covid19_chicago %>%  
     filter(date >= as.Date("2020-05-12") & date <= as.Date("2020-05-18")) %>% 
     summarize(
       week = 6,
        mortality = sum(deaths_total))
 
 row7 = covid19_chicago %>%  
     filter(date >= as.Date("2020-05-19") & date <= as.Date("2020-05-25")) %>% 
     summarize(
       week = 7,
        mortality = sum(deaths_total))
 
 covid19_chicago_df = bind_rows(row1, row2, row3, row4, row5, row6, row7)
 
plot_2 = 
  covid19_chicago_df %>% 
  plot_ly(
    x = ~week, y = ~ mortality, color = ~ mortality, type = "bar") %>% 
  layout(title = "Spanish Flu (left) vs COVID-19: Peak 7 weeks comparison (Chicago)")
```

```{r}
subplot(plot_1, plot_2, shareX = TRUE,  shareY = TRUE)
```



Basic Reproductive rate

```{r}
data_url = "https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30484-9/fulltext"
reproductive_rate_html = read_html(data_url)

table_r0 =
  reproductive_rate_html %>% 
  html_nodes(css = "table") %>%  
  first() %>%
  html_table() %>% 
  make_clean_names() %>% 
  select(-6) %>% 
  filter(x == "Transmissibility, R0" | x == "Incubation period, days" | x == "Interval between symptom onset and maximum infectivity, days" | x == "Proportion with mild illness") %>% 
  rename(
     covid_19 = sars_co_v_2,
     sars_2003 = sars_co_v,
     spanish_flu = pandemic_influenza_1918,
     h1n1_2009 = pandemic_influenza_2009
  ) %>% 
  mutate(x = replace(x, x == "Transmissibility, R0", "Basic Reproductive rate, R0")) %>% 
  as_tibble() 

table_r0 %>%
  filter(x == "Basic Reproductive rate, R0") %>%            
   pivot_longer(	
    covid_19:h1n1_2009,
    names_to = "pandemic",
    values_to = "r0"
    ) %>% 
  plot_ly(
    x = ~pandemic, y = ~r0, color = ~r0, type = "bar", ymin = 0) %>% 
  layout(title = "Comparing Reproductive rates", showlegend = FALSE)
  
table_r0 =
  table_r0 %>% 
  knitr::kable()

table_r0
```
